#!/usr/bin/env python3
"""
Setup ATPG testing environment for Verilog library cells.

This script traverses a directory hierarchy (e.g., skywater-pdk-libs-sky130_fd_sc_hdll),
finds directories containing Verilog library cells (.v files), creates 'xatpg'
subdirectories, and generates Makefiles to run FAN_ATPG tests.
"""

import os
import sys
import argparse
from pathlib import Path
from typing import List, Set


def find_verilog_files(directory: Path) -> List[Path]:
    """Find all Verilog (.v) files in the given directory (non-recursive for this dir)."""
    if not directory.is_dir():
        return []
    return list(directory.glob("*.v"))


def find_verilog_directories(root_path: Path, exclude_dirs: Set[str] = None) -> List[Path]:
    """
    Recursively find all directories containing Verilog (.v) files.

    Args:
        root_path: Root directory to start search
        exclude_dirs: Set of directory names to exclude (e.g., {'xatpg', '.git'})

    Returns:
        List of Path objects for directories containing .v files
    """
    if exclude_dirs is None:
        exclude_dirs = {'xatpg', '.git', '__pycache__', '.svn', 'CVS'}

    verilog_dirs = []

    try:
        for item in root_path.rglob("*.v"):
            parent_dir = item.parent

            # Skip if any parent directory is in exclude list
            if any(excluded in parent_dir.parts for excluded in exclude_dirs):
                continue

            if parent_dir not in verilog_dirs:
                verilog_dirs.append(parent_dir)
    except PermissionError as e:
        print(f"Warning: Permission denied accessing {e.filename}", file=sys.stderr)

    return sorted(verilog_dirs)


def create_atpg_makefile(xatpg_dir: Path, verilog_files: List[Path],
                         parent_dir: Path) -> None:
    """
    Create a Makefile in the xatpg directory for running FAN_ATPG tests.

    Args:
        xatpg_dir: Path to the xatpg subdirectory
        verilog_files: List of Verilog files to test
        parent_dir: Parent directory containing the Verilog files
    """

    # Get relative paths for Verilog files
    verilog_basenames = [vf.name for vf in verilog_files]
    verilog_stems = [vf.stem for vf in verilog_files]

    makefile_content = f"""# Makefile for FAN_ATPG testing
# Auto-generated for directory: {parent_dir}
# Generated by setup_verilog_atpg.py

# Configuration
VERILOG_DIR = ..
FAN_ATPG = fan_atpg
VERILOG_FILES = {' '.join(verilog_basenames)}

# Test targets (one per Verilog file)
TEST_TARGETS = {' '.join(f'{stem}.test' for stem in verilog_stems)}
REPORT_FILES = {' '.join(f'{stem}.rpt' for stem in verilog_stems)}

# Default target
.PHONY: all clean help test

all: test

# Run all ATPG tests
test: $(TEST_TARGETS)
\t@echo "All ATPG tests completed"

# Pattern rule for running FAN_ATPG on each Verilog file
%.test: $(VERILOG_DIR)/%.v
\t@echo "Running FAN_ATPG on $<"
\t$(FAN_ATPG) -i $< -o $*.rpt || true
\t@touch $@

# Individual test targets
"""

    # Add individual targets for each Verilog file
    for stem, basename in zip(verilog_stems, verilog_basenames):
        makefile_content += f"""
{stem}.test: $(VERILOG_DIR)/{basename}
\t@echo "Testing {basename}..."
\t@$(FAN_ATPG) -i $(VERILOG_DIR)/{basename} -o {stem}.rpt 2>&1 | tee {stem}.log || true
\t@touch $@
"""

    makefile_content += """
# Clean generated files
clean:
\trm -f $(TEST_TARGETS) $(REPORT_FILES) *.log *.atpg *.patterns

# Show help
help:
\t@echo "FAN_ATPG Makefile for Verilog library cells"
\t@echo ""
\t@echo "Targets:"
\t@echo "  all     - Run all ATPG tests (default)"
\t@echo "  test    - Run all ATPG tests"
\t@echo "  clean   - Remove generated test files"
\t@echo "  help    - Show this help message"
\t@echo ""
\t@echo "Individual tests:"
"""

    for stem in verilog_stems:
        makefile_content += f"\t@echo \"  {stem}.test\"\n"

    makefile_content += """
\t@echo ""
\t@echo "Verilog files:"
"""

    for basename in verilog_basenames:
        makefile_content += f"\t@echo \"  {basename}\"\n"

    # Write the Makefile
    makefile_path = xatpg_dir / "Makefile"
    with open(makefile_path, 'w') as f:
        f.write(makefile_content)

    print(f"  Created Makefile: {makefile_path}")


def create_atpg_readme(xatpg_dir: Path, parent_dir: Path, verilog_count: int) -> None:
    """Create a README file in the xatpg directory."""
    readme_content = f"""# FAN_ATPG Test Directory

This directory contains ATPG (Automatic Test Pattern Generation) tests
for the Verilog library cells in: {parent_dir}

## Contents

- **Makefile**: Build file for running FAN_ATPG tests
- **Verilog files**: {verilog_count} library cell(s) found in parent directory

## Usage

To run all ATPG tests:
```bash
make test
```

To run a specific test:
```bash
make <cellname>.test
```

To clean generated files:
```bash
make clean
```

To see all available targets:
```bash
make help
```

## Generated by

setup_verilog_atpg.py script from xyce-top/tests

"""

    readme_path = xatpg_dir / "README.md"
    with open(readme_path, 'w') as f:
        f.write(readme_content)

    print(f"  Created README: {readme_path}")


def setup_atpg_directory(verilog_dir: Path, dry_run: bool = False) -> bool:
    """
    Setup ATPG testing directory for a directory containing Verilog files.

    Args:
        verilog_dir: Directory containing Verilog files
        dry_run: If True, only print what would be done

    Returns:
        True if successful, False otherwise
    """
    verilog_files = find_verilog_files(verilog_dir)

    if not verilog_files:
        return False

    xatpg_dir = verilog_dir / "xatpg"

    print(f"\nProcessing: {verilog_dir}")
    print(f"  Found {len(verilog_files)} Verilog file(s)")

    if dry_run:
        print(f"  [DRY RUN] Would create: {xatpg_dir}")
        print(f"  [DRY RUN] Would generate Makefile for {len(verilog_files)} files")
        return True

    # Create xatpg subdirectory
    try:
        xatpg_dir.mkdir(exist_ok=True)
        print(f"  Created directory: {xatpg_dir}")
    except Exception as e:
        print(f"  Error creating directory {xatpg_dir}: {e}", file=sys.stderr)
        return False

    # Create Makefile
    try:
        create_atpg_makefile(xatpg_dir, verilog_files, verilog_dir)
    except Exception as e:
        print(f"  Error creating Makefile: {e}", file=sys.stderr)
        return False

    # Create README
    try:
        create_atpg_readme(xatpg_dir, verilog_dir, len(verilog_files))
    except Exception as e:
        print(f"  Error creating README: {e}", file=sys.stderr)
        return False

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Setup ATPG testing environment for Verilog library cells",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Setup ATPG for skywater PDK
  %(prog)s /path/to/skywater-pdk-libs-sky130_fd_sc_hdll

  # Dry run to see what would be done
  %(prog)s --dry-run /path/to/skywater-pdk-libs-sky130_fd_sc_hdll

  # Process specific directory
  %(prog)s ./verilog_lib
        """
    )

    parser.add_argument(
        'target_dir',
        type=str,
        help='Target directory to search for Verilog files (e.g., skywater-pdk-libs-sky130_fd_sc_hdll)'
    )

    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without making changes'
    )

    parser.add_argument(
        '--exclude',
        type=str,
        nargs='+',
        default=['xatpg', '.git', '__pycache__'],
        help='Directory names to exclude from search (default: xatpg .git __pycache__)'
    )

    parser.add_argument(
        '--verbose',
        '-v',
        action='store_true',
        help='Verbose output'
    )

    args = parser.parse_args()

    target_path = Path(args.target_dir).resolve()

    # Validate target directory
    if not target_path.exists():
        print(f"Error: Target directory does not exist: {target_path}", file=sys.stderr)
        return 1

    if not target_path.is_dir():
        print(f"Error: Target is not a directory: {target_path}", file=sys.stderr)
        return 1

    print("=" * 80)
    print("Verilog ATPG Setup Script")
    print("=" * 80)
    print(f"Target directory: {target_path}")
    print(f"Dry run: {args.dry_run}")
    print(f"Excluded directories: {', '.join(args.exclude)}")
    print("=" * 80)

    # Find all directories with Verilog files
    print("\nSearching for Verilog files...")
    verilog_dirs = find_verilog_directories(target_path, set(args.exclude))

    if not verilog_dirs:
        print(f"\nNo Verilog files found in {target_path}")
        return 0

    print(f"\nFound {len(verilog_dirs)} director{'y' if len(verilog_dirs) == 1 else 'ies'} containing Verilog files")

    # Setup ATPG for each directory
    success_count = 0
    for verilog_dir in verilog_dirs:
        if setup_atpg_directory(verilog_dir, args.dry_run):
            success_count += 1

    # Summary
    print("\n" + "=" * 80)
    print("Summary")
    print("=" * 80)
    print(f"Directories processed: {success_count}/{len(verilog_dirs)}")

    if args.dry_run:
        print("\n[DRY RUN] No changes were made. Run without --dry-run to apply changes.")
    else:
        print("\nSetup complete! ATPG directories and Makefiles have been created.")
        print("\nTo run tests in any xatpg directory:")
        print("  cd <directory>/xatpg")
        print("  make test")

    print("=" * 80)

    return 0 if success_count == len(verilog_dirs) else 1


if __name__ == "__main__":
    sys.exit(main())
