// Auto-generated Xyce wrapper for Verilator module: simple_inv
// Generated by verilog2xyce.pl

#include <iostream>
#include <vector>
#include <cstring>
#include <assert.h>
#include "simple_inv_xyce.h"

std::vector<Simple_invVerilator *> Simple_invDevices;
std::vector<Simple_invVerilator *> Simple_invDevicesTmp;

Simple_invVerilator::Simple_invVerilator()
    : verilator_model(new Vsimple_inv()),
      in_handler(NULL),
      out_handler(NULL),
      threshold(0.5)
{
}

Simple_invVerilator::~Simple_invVerilator() {
    delete verilator_model;
}

bool Simple_invVerilator::Finished() {
    return (
        NULL != in_handler &&
        NULL != out_handler &&
        out_handler->ready()    );
}

Simple_invPwlHandler::Simple_invPwlHandler(
    PWLinDynData *XyceSrc, Simple_invVerilator *pDevice,
    const char *pname, c_string args, double trigger, handler hndlr)
    : PwlHandler(XyceSrc, trigger, hndlr, args),
      device(pDevice),
      port_name(pname)
{
}

void Simple_invVerilator::Eval(double now) {
    if (!in_handler || !out_handler) return;

    // Get input: in
    double v_in = in_handler->startV();
    verilator_model->in = (v_in > threshold) ? 1 : 0;

    // Evaluate Verilator model
    verilator_model->eval();

    // Set output: out
    double v_out = verilator_model->out ? 1.0 : 0.0;
    tTVVEC *TV_out = out_handler->getTV();
    if (TV_out && TV_out->size() > 0) {
        TV_out->clear();
        TV_out->push_back(std::make_pair(now, v_out));
    }
    out_handler->update();

}

extern "C" {

// Input change handler
void Simple_invCross(PwlHandler *pwlh, double skew, double Vbegin, double Vend) {
    Simple_invPwlHandler *vpwlh = (Simple_invPwlHandler *)pwlh;
    Simple_invVerilator *dev = vpwlh->device;
    double now = vpwlh->endT();
    dev->Eval(now);
}

// Bridge functions for each port
int Simple_invBridge_in(PWLinDynData *XyceSrc, void *MyData, int op, void *data) {
    Simple_invVerilator *dev = (Simple_invVerilator *)MyData;
    return PwlBridge(XyceSrc, dev->in(), op, data);
}

int Simple_invBridge_out(PWLinDynData *XyceSrc, void *MyData, int op, void *data) {
    Simple_invVerilator *dev = (Simple_invVerilator *)MyData;
    return PwlBridge(XyceSrc, dev->out(), op, data);
}

// Attachment function (called by Xyce)
BridgeFn ConnectSimple_inv(PWLinDynData *XyceSrc, void **MyData, const char *args) {
    BridgeFn bFn = NULL;
    std::vector<Simple_invVerilator *>::iterator ii = Simple_invDevicesTmp.begin();
    bool new_dev = false;
    Simple_invVerilator *dev, *check = NULL;

    if (ii == Simple_invDevicesTmp.end()) {
        dev = new Simple_invVerilator();
        PwlHandler::setFns(MyData);
        Simple_invDevicesTmp.insert(Simple_invDevicesTmp.begin(), dev);
    } else {
        dev = *ii;
    }

    // Parse port name from args
    if (0 == strncasecmp(args, "out", strlen("out"))) {
        if (new_dev = (NULL != dev->out())) {
            check = dev;
            dev = new Simple_invVerilator();
        }
        while (*args && *args++ != ',');
        dev->set_out(new Simple_invPwlHandler(XyceSrc, dev, "out", args));
        bFn = Simple_invBridge_out;
    }
    else if (0 == strncasecmp(args, "in", strlen("in"))) {
        if (new_dev = (NULL != dev->in())) {
            check = dev;
            dev = new Simple_invVerilator();
        }
        while (*args && *args++ != ',');
        dev->set_in(new Simple_invPwlHandler(XyceSrc, dev, "in", args,
                   TRIG_MODE(TRIG_ALWAYS), Simple_invCross));
        bFn = Simple_invBridge_in;
    }

    if (NULL != check) {
        if (check->Finished()) {
            assert(*ii == check);
            Simple_invDevicesTmp.erase(ii);
            Simple_invDevices.push_back(check);
        }
    }

    if (new_dev) {
        Simple_invDevicesTmp.insert(Simple_invDevicesTmp.begin(), dev);
    }
    else {
        if (dev->Finished()) {
            assert(*ii == dev);
            Simple_invDevicesTmp.erase(ii);
            Simple_invDevices.push_back(dev);
        }
    }

    *MyData = dev;
    return bFn;
}

}  // extern "C"
