// Auto-generated Xyce wrapper for Verilator module: simple_inv
// Generated by verilog2xyce.pl

#ifndef SIMPLE_INV_XYCE_H
#define SIMPLE_INV_XYCE_H

#include "xbridge.h"
#include "Vsimple_inv.h"
#include <vector>

class Simple_invVerilator;
class Simple_invPwlHandler;

// Verilator module wrapper
class Simple_invVerilator {
protected:
    Vsimple_inv* verilator_model;
    Simple_invPwlHandler *in_handler;
    Simple_invPwlHandler *out_handler;
    double threshold;  // Voltage threshold for digital conversion

public:
    Simple_invVerilator();
    ~Simple_invVerilator();

    inline void set_in(Simple_invPwlHandler *h) { in_handler = h; }
    inline Simple_invPwlHandler *in() const { return in_handler; }
    inline void set_out(Simple_invPwlHandler *h) { out_handler = h; }
    inline Simple_invPwlHandler *out() const { return out_handler; }

    bool Finished();
    void Eval(double now);
};

// PWL handler for Verilator devices
class Simple_invPwlHandler : public PwlHandler {
public:
    Simple_invVerilator *device;
    const char *port_name;

    Simple_invPwlHandler(PWLinDynData *XyceSrc, Simple_invVerilator *pDevice,
                    const char *pname, c_string args = NULL,
                    double trigger = TRIG_MODE(TRIG_NEVER),
                    handler hndlr = NULL);
};

#endif // SIMPLE_INV_XYCE_H
