#!/usr/bin/env perl

#
# verilog2xyce.pl - Generate Xyce wrapper files for Verilator modules
#
# This script generates the necessary files to integrate a Verilator-compiled
# Verilog module with Xyce circuit simulator:
#   - .h header file with C++ class definitions
#   - .C implementation file with PWL bridge
#   - .cir Xyce netlist file
#

use strict;
use warnings;
use Getopt::Long;
use File::Basename;
use Cwd 'abs_path';

my $module_name = '';
my $verilog_file = '';
my $output_dir = '.';
my $help = 0;
my $stimulate = 0;

GetOptions(
    'module|m=s'  => \$module_name,
    'verilog|v=s' => \$verilog_file,
    'output|o=s'  => \$output_dir,
    'stim|s=s'    => \$stimulate,
    'help|h'      => \$help,
) or die "Error in command line arguments\n";

if ($help || !$module_name) {
    print_usage();
    exit 0;
}

# If verilog file not specified, try to find it
if (!$verilog_file) {
    $verilog_file = "$module_name.v";
    die "Error: Verilog file $verilog_file not found\n" unless -f $verilog_file;
}

# Parse the Verilog file to extract port information
my ($inputs_ref, $outputs_ref) = parse_verilog($verilog_file, $module_name);
my @inputs = @$inputs_ref;
my @outputs = @$outputs_ref;

print "Module: $module_name\n";
print "Inputs: ", join(", ", @inputs), "\n";
print "Outputs: ", join(", ", @outputs), "\n";

# Generate the files
my $suffix = "_xyce";
my $base_name = $module_name;
my $verilator_class = "V$module_name";
my $so_file = "${base_name}${suffix}.so";

generate_header($base_name, $module_name, $verilator_class, \@inputs, \@outputs);
generate_implementation($base_name, $module_name, $verilator_class, \@inputs, \@outputs);
generate_netlist($base_name, $module_name, $so_file, \@inputs, \@outputs);

print "\nGenerated files:\n";
print "  ${base_name}$suffix.h\n";
print "  ${base_name}$suffix.C\n";
print "  ${base_name}.cir\n";
print "\nNext steps:\n";
print "  1. Run Verilator: verilator --cc -CFLAGS \"-fPIC\" $verilog_file\n";
print "  2. Build Verilator library: make -C obj_dir -f ${verilator_class}.mk\n";
print "  3. Build shared library: make ${so_file}\n";
print "  4. Run Xyce: Xyce ${base_name}.cir\n";

sub parse_verilog {
    my ($file, $module) = @_;
    my @inputs;
    my @outputs;

    open(my $fh, '<', $file) or die "Cannot open $file: $!\n";

    my $in_module = 0;
    my $in_ports = 0;
    my $port_text = '';

    while (my $line = <$fh>) {
        # Remove comments
        $line =~ s/\/\/.*$//;
        $line =~ s/\/\*.*?\*\///g;

        if ($line =~ /^\s*module\s+$module\s*(\(|;)/) {
            $in_module = 1;
            $in_ports = 1 if $line =~ /\(/;
            $port_text = $line;
        }
        elsif ($in_ports) {
            $port_text .= $line;
            if ($line =~ /\);/) {
                $in_ports = 0;
            }
        }
        elsif ($in_module) {
            if ($line =~ /^\s*input\s+(?:wire\s+)?(?:\[.*?\]\s+)?(\w+)/) {
                push @inputs, $1;
            }
            elsif ($line =~ /^\s*output\s+(?:wire\s+)?(?:reg\s+)?(?:\[.*?\]\s+)?(\w+)/) {
                push @outputs, $1;
            }
            elsif ($line =~ /^\s*endmodule/) {
                last;
            }
        }
    }

    close($fh);

    # Parse port list if we collected it
    if ($port_text && !@inputs && !@outputs) {
        # Extract port list between parentheses
        if ($port_text =~ /\((.*?)\)/s) {
            my $ports = $1;
            # Look for input/output declarations in port list
            while ($ports =~ /input\s+(?:\w+\s+)?(?:\[.*?\]\s+)?(\w+)/g) {
                push @inputs, $1;
            }
            while ($ports =~ /output\s+(?:\w+\s+)?(?:\[.*?\]\s+)?(\w+)/g) {
                push @outputs, $1;
            }
        }
    }

    return (\@inputs, \@outputs);
}

sub generate_header {
    my ($base_name, $module, $verilator_class, $inputs_ref, $outputs_ref) = @_;
    my @inputs = @$inputs_ref;
    my @outputs = @$outputs_ref;

    my $header = uc($base_name) . "_H";
    my $class_name = ucfirst($module);

    open(my $fh, '>', "${base_name}${suffix}.h") or die "Cannot create ${base_name}.h: $!\n";

    print $fh <<EOF;
// Auto-generated Xyce wrapper for Verilator module: $module
// Generated by verilog2xyce.pl

#ifndef ${header}
#define ${header}

#include "xbridge.h"
#include "${verilator_class}.h"
#include <vector>

class ${class_name}Verilator;
class ${class_name}PwlHandler;

// Verilator module wrapper
class ${class_name}Verilator {
protected:
    ${verilator_class}* verilator_model;
EOF

    # Generate handler pointers for each port
    print $fh "    ${class_name}PwlHandler *vdd_handler;\n";
    for my $in (@inputs) {
        print $fh "    ${class_name}PwlHandler *${in}_handler;\n";
    }
    for my $out (@outputs) {
        print $fh "    ${class_name}PwlHandler *${out}_handler;\n";
    }

    print $fh <<EOF;
    double threshold;  // Voltage threshold for digital conversion

public:
    ${class_name}Verilator();
    ~${class_name}Verilator();

EOF

    # Generate setters/getters
    print $fh "    inline void set_vdd(${class_name}PwlHandler *h) { vdd_handler = h; }\n";
    print $fh "    inline ${class_name}PwlHandler *vdd() const { return vdd_handler; }\n";
    for my $in (@inputs) {
        print $fh "    inline void set_${in}(${class_name}PwlHandler *h) { ${in}_handler = h; }\n";
        print $fh "    inline ${class_name}PwlHandler *${in}() const { return ${in}_handler; }\n";
    }
    for my $out (@outputs) {
        print $fh "    inline void set_${out}(${class_name}PwlHandler *h) { ${out}_handler = h; }\n";
        print $fh "    inline ${class_name}PwlHandler *${out}() const { return ${out}_handler; }\n";
    }

    print $fh <<EOF;

    bool Finished();
    void Eval(double now);
};

// PWL handler for Verilator devices
class ${class_name}PwlHandler : public PwlHandler {
public:
    ${class_name}Verilator *device;
    const char *port_name;

    ${class_name}PwlHandler(PWLinDynData *XyceSrc, ${class_name}Verilator *pDevice,
                    const char *pname, c_string args = NULL,
                    double trigger = TRIG_MODE(TRIG_NEVER),
                    handler hndlr = NULL);
};

#endif // ${header}
EOF

    close($fh);
}

sub generate_implementation {
    my ($base_name, $module, $verilator_class, $inputs_ref, $outputs_ref) = @_;
    my @inputs = @$inputs_ref;
    my @outputs = @$outputs_ref;
    my $class_name = ucfirst($module);

    open(my $fh, '>', "${base_name}${suffix}.C") or die "Cannot create ${base_name}.C: $!\n";

    print $fh <<EOF;
// Auto-generated Xyce wrapper for Verilator module: $module
// Generated by verilog2xyce.pl

#include <iostream>
#include <vector>
#include <cstring>
#include <assert.h>
#include "${base_name}${suffix}.h"

std::vector<${class_name}Verilator *> ${class_name}Devices;
std::vector<${class_name}Verilator *> ${class_name}DevicesTmp;

${class_name}Verilator::${class_name}Verilator()
    : verilator_model(new ${verilator_class}()),
EOF

    # Initialize handlers to NULL
    print $fh "      vdd_handler(NULL),\n";
    for my $in (@inputs) {
        print $fh "      ${in}_handler(NULL),\n";
    }
    for my $out (@outputs) {
        print $fh "      ${out}_handler(NULL),\n";
    }

    print $fh <<EOF;
      threshold(0.5)
{
}

${class_name}Verilator::~${class_name}Verilator() {
    delete verilator_model;
}

bool ${class_name}Verilator::Finished() {
    return (
EOF

    # Check all handlers are ready (including vdd)
    my @all_ports = ('vdd', @inputs, @outputs);
    print $fh "        NULL != " . join("_handler &&\n        NULL != ", @all_ports) . "_handler";
    if (@outputs) {
        print $fh " &&\n        " . $outputs[0] . "_handler->ready()";
    }

    print $fh <<EOF;
    );
}

${class_name}PwlHandler::${class_name}PwlHandler(
    PWLinDynData *XyceSrc, ${class_name}Verilator *pDevice,
    const char *pname, c_string args, double trigger, handler hndlr)
    : PwlHandler(XyceSrc, trigger, hndlr, args),
      device(pDevice),
      port_name(pname)
{
}

void ${class_name}Verilator::Eval(double now) {
EOF

    # Check handlers (vdd is optional for Eval since it's just monitored)
    my @required_ports = (@inputs, @outputs);
    print $fh "    if (!" . join("_handler || !", @required_ports) . "_handler) return;\n\n";

    # Read inputs and convert to digital
    for my $in (@inputs) {
        print $fh "    // Get input: $in\n";
        print $fh "    double v_$in = ${in}_handler->startV();\n";
        print $fh "    verilator_model->$in = (v_$in > threshold) ? 1 : 0;\n\n";
    }

    print $fh <<EOF;
    // Evaluate Verilator model
    verilator_model->eval();

EOF

    # Convert outputs to analog
    for my $out (@outputs) {
        print $fh "    // Set output: $out\n";
        print $fh "    double v_$out = verilator_model->$out ? 1.0 : 0.0;\n";
        print $fh "    tTVVEC *TV_$out = ${out}_handler->getTV();\n";
        print $fh "    if (TV_$out && TV_${out}->size() > 0) {\n";
        print $fh "        TV_${out}->clear();\n";
        print $fh "        TV_${out}->push_back(std::make_pair(now, v_${out}));\n";
        print $fh "    }\n";
        print $fh "    ${out}_handler->update();\n\n";
    }

    print $fh <<EOF;
}

extern "C" {

// Input change handler
void ${class_name}Cross(PwlHandler *pwlh, double skew, double Vbegin, double Vend) {
    ${class_name}PwlHandler *vpwlh = (${class_name}PwlHandler *)pwlh;
    ${class_name}Verilator *dev = vpwlh->device;
    double now = vpwlh->endT();
    dev->Eval(now);
}

// Bridge functions for each port
EOF

    my $port_idx = 0;
    # Bridge function for VDD
    print $fh <<EOF;
int ${class_name}Bridge_vdd(PWLinDynData *XyceSrc, void *MyData, int op, void *data) {
    ${class_name}Verilator *dev = (${class_name}Verilator *)MyData;
    return PwlBridge(XyceSrc, dev->vdd(), op, data);
}

EOF
    $port_idx++;

    for my $in (@inputs) {
        print $fh <<EOF;
int ${class_name}Bridge_${in}(PWLinDynData *XyceSrc, void *MyData, int op, void *data) {
    ${class_name}Verilator *dev = (${class_name}Verilator *)MyData;
    return PwlBridge(XyceSrc, dev->${in}(), op, data);
}

EOF
        $port_idx++;
    }

    for my $out (@outputs) {
        print $fh <<EOF;
int ${class_name}Bridge_${out}(PWLinDynData *XyceSrc, void *MyData, int op, void *data) {
    ${class_name}Verilator *dev = (${class_name}Verilator *)MyData;
    return PwlBridge(XyceSrc, dev->${out}(), op, data);
}

EOF
        $port_idx++;
    }

    print $fh <<EOF;
// Attachment function (called by Xyce)
BridgeFn Connect${class_name}(PWLinDynData *XyceSrc, void **MyData, const char *args) {
    BridgeFn bFn = NULL;
    std::vector<${class_name}Verilator *>::iterator ii = ${class_name}DevicesTmp.begin();
    bool new_dev = false;
    ${class_name}Verilator *dev, *check = NULL;

    if (ii == ${class_name}DevicesTmp.end()) {
        dev = new ${class_name}Verilator();
        PwlHandler::setFns(MyData);
        ${class_name}DevicesTmp.insert(${class_name}DevicesTmp.begin(), dev);
    } else {
        dev = *ii;
    }

    // Parse port name from args
EOF

    for my $out (@outputs) {
        print $fh <<EOF;
    if (0 == strncasecmp(args, "$out", strlen("$out"))) {
        if (new_dev = (NULL != dev->${out}())) {
            check = dev;
            dev = new ${class_name}Verilator();
        }
        while (*args && *args++ != ',');
        dev->set_${out}(new ${class_name}PwlHandler(XyceSrc, dev, "$out", args));
        bFn = ${class_name}Bridge_${out};
    }
EOF
    }

    # Add handler for VDD voltage monitoring
    print $fh <<EOF;
    else if (0 == strncasecmp(args, "vdd", strlen("vdd"))) {
        if (new_dev = (NULL != dev->vdd())) {
            check = dev;
            dev = new ${class_name}Verilator();
        }
        while (*args && *args++ != ',');
        dev->set_vdd(new ${class_name}PwlHandler(XyceSrc, dev, "vdd", args));
        bFn = ${class_name}Bridge_vdd;
    }
EOF

    for my $in (@inputs) {
        print $fh <<EOF;
    else if (0 == strncasecmp(args, "$in", strlen("$in"))) {
        if (new_dev = (NULL != dev->${in}())) {
            check = dev;
            dev = new ${class_name}Verilator();
        }
        while (*args && *args++ != ',');
        dev->set_${in}(new ${class_name}PwlHandler(XyceSrc, dev, "$in", args,
                   TRIG_MODE(TRIG_ALWAYS), ${class_name}Cross));
        bFn = ${class_name}Bridge_${in};
    }
EOF
    }

    print $fh <<EOF;

    if (NULL != check) {
        if (check->Finished()) {
            assert(*ii == check);
            ${class_name}DevicesTmp.erase(ii);
            ${class_name}Devices.push_back(check);
        }
    }

    if (new_dev) {
        ${class_name}DevicesTmp.insert(${class_name}DevicesTmp.begin(), dev);
    }
    else {
        if (dev->Finished()) {
            assert(*ii == dev);
            ${class_name}DevicesTmp.erase(ii);
            ${class_name}Devices.push_back(dev);
        }
    }

    *MyData = dev;
    return bFn;
}

}  // extern "C"
EOF

    close($fh);
}

sub generate_netlist {
    my ($base_name, $module, $so_file, $inputs_ref, $outputs_ref) = @_;
    my @inputs = @$inputs_ref;
    my @outputs = @$outputs_ref;
    my $class_name = ucfirst($module);
    my $stimulate = 0;  # Don't generate stimulus by default

    open(my $fh, '>', "${base_name}.cir") or die "Cannot create ${base_name}.cir: $!\n";

    print $fh <<EOF;
* Auto-generated Xyce subcircuit for Verilator module: $module
* Generated by verilog2xyce.pl

* $module Verilator Subcircuit

EOF

    print $fh ".SUBCKT $module VDD OUT IN\n\n";

    if ($stimulate) {
	# Generate stimulus for inputs
	my $time = 0;
	for my $in (@inputs) {
	    $time += 1;
	    print $fh "* Input stimulus for $in\n";
	    print $fh "Vin_$in ${in}_node 0 PULSE(0 1 ${time}n 0.1n 0.1n 5n 10n)\n\n";
	}
    }
    
    # Generate device instances
    print $fh "* $module device using Verilator (ports via PWL bridge)\n";
    my $n = 1;
    # IPWL for VDD voltage monitoring
    print $fh "IPWL$n VDD 0 PWL FILE \"code:./$so_file:Connect${class_name}:vdd\"\n";
    $n++;
    for my $in (@inputs) {
        print $fh "IPWL$n ${module}_${in} 0 PWL FILE \"code:./$so_file:Connect${class_name}:$in\"\n";
	$n++;
    }
    for my $out (@outputs) {
        print $fh "VPWL$n ${module}_${out} 0 PWL FILE \"code:./$so_file:Connect${class_name}:$out\"\n";
	$n++;
    }

    print $fh "\n.ENDS\n\n";

    # Load resistors for outputs
    for my $out (@outputs) {
        print $fh "Rload_$out ${out}_node 0 1k\n";
    }

    if ($stimulate) {
	print $fh "\n* Transient analysis\n";
	print $fh ".tran 0.1n 30n\n\n";
	print $fh "* Output\n";
	print $fh ".print tran ";
	print $fh join(" ", map { "v(${_}_node)" } @inputs);
	print $fh " ";
	print $fh join(" ", map { "v(${_}_node)" } @outputs);
	print $fh "\n\n.end\n";
    }
    
    close($fh);
}

sub print_usage {
    print <<'USAGE';
Usage: verilog2xyce.pl -m MODULE_NAME [OPTIONS]

Generate Xyce wrapper files for Verilator-compiled Verilog modules

Options:
  -m, --module MODULE   Module name (required)
  -v, --verilog FILE    Verilog source file (default: MODULE.v)
  -o, --output DIR      Output directory (default: current directory)
  -h, --help            Show this help message

Example:
  verilog2xyce.pl -m simple_inv -v simple_inv.v

This generates:
  simple_inv_xyce.h    - C++ header file
  simple_inv_xyce.C    - C++ implementation
  simple_inv_xyce.cir  - Xyce netlist

USAGE
}
