#!/usr/bin/env perl
#
# xyce_test2external.pl
#
# Convert Xyce test circuits to use external Verilator logic elements
# Takes an existing .cir file and creates a modified version that uses
# IPWL/VPWL external devices instead of internal models
#

use strict;
use warnings;
use File::Basename;
use File::Copy;
use Getopt::Long;

my $help = 0;
my $verbose = 0;
my $output_dir = '.';
my $module_name = '';

GetOptions(
    'help|h'        => \$help,
    'verbose|v'     => \$verbose,
    'output|o=s'    => \$output_dir,
    'module|m=s'    => \$module_name,
) or die "Error in command line arguments\n";

if ($help || @ARGV == 0) {
    print_usage();
    exit($help ? 0 : 1);
}

my $input_cir = shift @ARGV;

unless (-f $input_cir) {
    die "Error: Input circuit file not found: $input_cir\n";
}

# Create output directory if needed
unless (-d $output_dir) {
    mkdir $output_dir or die "Cannot create output directory $output_dir: $!\n";
}

# Determine output filename
my $basename = basename($input_cir, '.cir');
my $output_cir = "$output_dir/${basename}_external.cir";

print "Converting $input_cir to use external devices...\n" if $verbose;
print "Output: $output_cir\n" if $verbose;

# Convert the circuit
convert_to_external($input_cir, $output_cir, $module_name);

print "Conversion complete!\n" if $verbose;

exit 0;

# Subroutines

sub convert_to_external {
    my ($input, $output, $module) = @_;

    open(my $in_fh, '<', $input) or die "Cannot open $input: $!\n";
    open(my $out_fh, '>', $output) or die "Cannot create $output: $!\n";

    my %replacements;  # Track what we've replaced
    my $device_count = 0;

    # Determine module name if not specified
    unless ($module) {
        $module = 'logic_gate';
    }

    my $so_file = "${module}.so";

    print $out_fh "* Modified to use external Verilator logic devices\n";
    print $out_fh "* Original: $input\n";
    print $out_fh "* Generated by xyce_test2external.pl\n";
    print $out_fh "\n";

    while (my $line = <$in_fh>) {
        # Skip existing title/comment lines that we've already added
        if ($. <= 3 && $line =~ /^\*/s) {
            next;
        }

        # Check if this is a device that can be replaced with external model
        # Look for common devices: resistors (R), capacitors (C), voltage sources (V), etc.
        # For logic gates, look for subcircuit calls (X) or digital devices

        if ($line =~ /^X(\S+)\s+(.+?)\s+(\S+)\s*$/i) {
            # Subcircuit call - could be a logic gate
            my ($inst_name, $net_list, $subckt_name) = ($1, $2, $3);

            # Check if this is a logic gate subcircuit
            if ($subckt_name =~ /^(inv|and|or|nand|nor|xor|buf)/i) {
                my $gate_type = lc($1);
                my @nets = split(/\s+/, $net_list);

                # Replace with external device
                print $out_fh "* Original: $line";
                print $out_fh convert_to_pwl_bridge($inst_name, \@nets, $gate_type, $so_file, $module);

                $replacements{$subckt_name}++;
                $device_count++;
                next;
            }
        }
        # Check for digital devices (Y prefix in Xyce)
        elsif ($line =~ /^Y(\S+)\s+(\S+)\s+(.+?)\s+(\S+)\s*$/i) {
            # Digital device: YINST type nodes... model
            my ($inst_name, $type, $net_list, $model) = ($1, $2, $3, $4);

            if ($type =~ /^(INV|AND|OR|NAND|NOR|XOR|BUF)/i) {
                my $gate_type = lc($1);
                my @nets = split(/\s+/, $net_list);

                # Replace with external device
                print $out_fh "* Original: $line";
                print $out_fh convert_to_pwl_bridge($inst_name, \@nets, $gate_type, $so_file, $module);

                $replacements{$type}++;
                $device_count++;
                next;
            }
        }

        # Pass through all other lines unchanged
        print $out_fh $line;
    }

    close($in_fh);
    close($out_fh);

    # Print summary
    if ($verbose && %replacements) {
        print "\nReplaced devices:\n";
        foreach my $type (sort keys %replacements) {
            print "  $type: $replacements{$type}\n";
        }
        print "Total: $device_count device(s) converted to external\n";
    }
}

sub convert_to_pwl_bridge {
    my ($inst_name, $nets_ref, $gate_type, $so_file, $module) = @_;
    my @nets = @$nets_ref;

    my $result = "";

    # Assume last net is output, others are inputs
    my $output_net = pop @nets;
    my @input_nets = @nets;

    # Generate IPWL for inputs and VPWL for output
    my $class_name = ucfirst($module);

    foreach my $i (0..$#input_nets) {
        my $in_net = $input_nets[$i];
        my $port_name = chr(65 + $i);  # A, B, C, ...
        $result .= "IPWL ${inst_name}_${port_name} ${in_net} \"code:./$so_file!Connect${class_name}:${port_name}\"\n";
    }

    # Output
    $result .= "VPWL ${inst_name}_Y ${output_net} \"code:./$so_file!Connect${class_name}:Y\"\n";
    $result .= "\n";

    return $result;
}

sub print_usage {
    print <<'USAGE';
Usage: xyce_test2external.pl [OPTIONS] input.cir

Convert Xyce test circuits to use external Verilator logic devices

Arguments:
  input.cir       Input Xyce circuit file

Options:
  --output, -o DIR    Output directory (default: current directory)
  --module, -m NAME   Verilog module name for external device (default: logic_gate)
  --verbose, -v       Verbose output
  --help, -h          Show this help message

Example:
  xyce_test2external.pl -o external_tests -m simple_inv mytest.cir

This will create mytest_external.cir that uses external Verilator devices
instead of internal Xyce models. You'll need to have the .so file built
from the Verilog module.

USAGE
}
